### ISSUE TITLE
NameError: name 'prime' is not defined

### ISSUE THREAD

**Issue by nickbelomatis** [sinanatra/tsne#1]
NameError                                 Traceback (most recent call last)
[<ipython-input-31-5913349afa57>](https://localhost:8080/#) in <module>()
      4 ny = 20
      5 
----> 6 grid_assignment = rasterfairy.transformPointCloud2D(tsne)

1 frames
[/usr/local/lib/python3.7/dist-packages/rasterfairy/rasterfairy.py](https://localhost:8080/#) in getRectArrangements(n)
    368 
    369 def getRectArrangements(n):
--> 370     p = prime.Prime()
    371     f = p.getPrimeFactors(n)
    372     f_count = len(f)

NameError: name 'prime' is not defined

**Comment by sinanatra** [comment]
did you install rasterfairy? then, if it is a problem with that library open an issue [there](https://github.com/Quasimondo/RasterFairy)

**Comment by nickbelomatis** [comment]
> did you install rasterfairy? then, if it is a problem with that library open an issue [there](https://github.com/Quasimondo/RasterFairy)

I solved it by just write this line "from rasterfairy import prime"
